# Generated by Django 2.1 on 2018-08-20 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300, verbose_name='问题')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('userpass', models.CharField(max_length=30, verbose_name='密码')),
                ('useremail', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('usertype', models.CharField(max_length=30, verbose_name='用户类型')),
                ('adddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期1')),
            ],
        ),
    ]
