# Generated by Django 2.1 on 2018-08-20 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adddate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期'),
        ),
    ]
