# Generated by Django 2.1 on 2018-08-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_remove_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
