# Generated by Django 2.1 on 2018-08-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='parent_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_level', to='assets.BusinessUnit', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='磁盘容量（GB）'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存大小（GB）'),
        ),
    ]
