# Generated by Django 2.1 on 2018-08-22 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180822_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassettoapprove',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Manufacturer', verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='内存大小（GB）'),
        ),
    ]
