# Generated by Django 2.1 on 2018-08-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180822_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassettoapprove',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='生产厂商'),
        ),
    ]
