# Generated by Django 2.1 on 2018-08-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20180822_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassettoapprove',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Manufacturer', verbose_name='制造商'),
        ),
    ]
