# Generated by Django 2.1 on 2018-08-23 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20180823_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='manufacturer',
        ),
    ]
