# Generated by Django 2.1 on 2018-08-23 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_ram_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Manufacturer', verbose_name='制造商2'),
        ),
    ]
