# Generated by Django 2.1 on 2018-08-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20180823_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='manufacturer',
        ),
    ]
