# Generated by Django 2.1 on 2018-08-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_ram_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='manufacturer',
            new_name='manufacturer_id',
        ),
    ]
